DROP TABLE IF EXISTS `logger_testing`;
DROP TABLE IF EXISTS `test`;
DROP TABLE IF EXISTS `test_one`;
DROP TABLE IF EXISTS `test_two`;
DROP TABLE IF EXISTS `test_three`;
CREATE TABLE IF NOT EXISTS `test` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`time`	INTEGER NOT NULL,
	`level`	INTEGER NOT NULL DEFAULT 0,
	`event`	TEXT NOT NULL,
	`message`	TEXT NOT NULL
);